// documentConstants.js

export const DOCUMENT_PROCESS_REQUEST = 'DOCUMENT_PROCESS_REQUEST'
export const DOCUMENT_PROCESS_SUCCESS = 'DOCUMENT_PROCESS_SUCCESS'
export const DOCUMENT_PROCESS_FAIL = 'DOCUMENT_PROCESS_FAIL'
